"""empty message

Revision ID: c9f8e317dba9
Revises: 
Create Date: 2017-01-22 17:59:19.027560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f8e317dba9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('entry', sa.Column('response_time', sa.Integer(), nullable=True))
    op.add_column('entry', sa.Column('review', sa.Integer(), nullable=True))
    op.drop_column('profile_analysis', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_analysis', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('entry', 'review')
    op.drop_column('entry', 'response_time')
    op.drop_column('entry', 'rating')
    # ### end Alembic commands ###
