"""empty message

Revision ID: cf26d6d0049c
Revises: 
Create Date: 2017-01-23 03:16:05.689644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf26d6d0049c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'id')
    op.add_column('profile_analysis', sa.Column('entry_url', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile_analysis', 'entry', ['entry_url'], ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_analysis', type_='foreignkey')
    op.drop_column('profile_analysis', 'entry_url')
    op.add_column('entry', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
