"""empty message

Revision ID: ef6857362ef9
Revises: 
Create Date: 2017-01-23 18:22:46.868618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6857362ef9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'id')
    op.add_column('profile_analysis', sa.Column('entry_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'profile_analysis', 'entry', ['entry_url'], ['url'])
    op.drop_column('profile_analysis', 'response_time_max')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_analysis', sa.Column('response_time_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profile_analysis', type_='foreignkey')
    op.drop_column('profile_analysis', 'entry_url')
    op.add_column('entry', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
